title: Human Interactions Robotics Laboratory
short_title: HIRo
description: Human Interactions Robotics Laboratory at Olin College specializes in innovative research to support the human-robot interaction field. We are interested in advancing research in areas relevant to path planning, perception as well as AI/ML and regularly develop new collaborative projects to accomplish this goal. Students in the Olin Robotics Lab can get access to cutting edge technologies to further their learning endeavors.
baseurl: "/hiro"
github: https://github.com/olinrobotics
olinrobot_name: Olin Robotics Lab
olin_web: http://olin.edu
olinrobot_web: https://olinrobotics.github.io/
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
exclude:
  - vendor/bundle
