controller_list:
  - name: "left_arm"
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: "right_arm"
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: "left_gripper"
    joints:
      - lgripper_finger_joint
  - name: "right_gripper"
    joints:
      - rgripper_finger_joint