<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="xamyab">

    <xacro:arg name="limited" default="true"/>
    <xacro:arg name="grippers" default="3"/>
    <xacro:arg name="sim" default="false"/>
    <xacro:property name="limited" value="$(arg limited)"/>
    <xacro:property name="grippers" value="$(arg grippers)"/>
    <xacro:property name="sim" value="$(arg sim)"/>

    <!--############## IMPORT STUFF ##############-->
    <!-- common stuff -->
    <xacro:include filename="$(find hiro_core)/urdf/common.gazebo.xacro"/>

    <!-- ground -->
    <xacro:include filename="$(find hiro_core)/urdf/ground.urdf.xacro"/>

    <!-- ur5 -->
    <xacro:include filename="$(find ur_description)/urdf/ur5.xacro"/>

    <!-- body -->
    <xacro:include filename="$(find hiro_core)/urdf/xamyab_body.urdf.xacro"/>

    <!-- robotiq 2f 140 gripper -->
    <xacro:if value="${grippers != 0}">
        <xacro:include
                filename="$(find robotiq_2f_140_gripper_visualization)/urdf/robotiq_arg2f_140_model_macro.xacro"/>
    </xacro:if>

    <xacro:macro name="xamyab_robot" params="joint_limited grippers">
        <!--############## INITIALIZATION ##############-->
        <!--ground -->
        <xacro:ground/>

        <!-- left arm -->
        <xacro:unless value="${joint_limited}">
            <xacro:ur5_robot prefix="left_" joint_limited="false"/>
        </xacro:unless>
        <xacro:if value="${joint_limited}">
            <xacro:ur5_robot prefix="left_" joint_limited="true"
                             shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
                             shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
                             elbow_joint_lower_limit="${-pi}" elbow_joint_upper_limit="${pi}"
                             wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
                             wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
                             wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>
        </xacro:if>
        <!-- right arm -->
        <xacro:unless value="${joint_limited}">
            <xacro:ur5_robot prefix="right_" joint_limited="false"/>
        </xacro:unless>
        <xacro:if value="${joint_limited}">
            <xacro:ur5_robot prefix="right_" joint_limited="true"
                             shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
                             shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
                             elbow_joint_lower_limit="${-pi}" elbow_joint_upper_limit="${pi}"
                             wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
                             wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
                             wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>
        </xacro:if>

        <!--############## CONNECT LINKS ##############-->
        <!-- arm body: Origin is the center of the bottom of the box -->
        <xacro:property name="width" value="0.3048"/>
        <xacro:property name="depth" value="0.3048"/>
        <xacro:property name="height" value="0.5755"/>
        <xacro:xamyab_body width="${width}" depth="${depth}" height="${height}"/>

        <link name="world"/>

        <joint name="ground_world_joint" type="fixed">
            <parent link="world"/>
            <child link="ground_base_link"/>
            <origin xyz="0 0 0.0001" rpy="0 0 0"/>
        </joint>

        <joint name="body_ground_joint" type="fixed">
            <parent link="ground_base_link"/>
            <child link="body_base_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <joint name="left_body_joint" type="fixed">
            <parent link="body_base_link"/>
            <child link="left_base_link"/>
            <origin xyz="${width / 2 - 0.105} ${depth / 2} 0.5134" rpy="${-pi / 2} ${-pi / 2} 0"/>
        </joint>

        <joint name="right_body_joint" type="fixed">
            <parent link="body_base_link"/>
            <child link="right_base_link"/>
            <origin xyz="${width / 2 - 0.105} ${-depth / 2} 0.5134" rpy="${pi / 2} ${pi / 2} 0"/>
        </joint>

        <!-- left gripper -->
        <xacro:if value="${grippers == 1 or grippers == 3}">
            <xacro:robotiq_arg2f_140 prefix="lgripper_"/>
            <joint name="lgripper_left_joint" type="fixed">
                <parent link="left_tool0"/>
                <child link="lgripper_robotiq_arg2f_base_link"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </joint>
        </xacro:if>

        <!-- right gripper -->
        <xacro:if value="${grippers == 2 or grippers == 3}">
            <xacro:robotiq_arg2f_140 prefix="rgripper_"/>
            <joint name="rgripper_right_joint" type="fixed">
                <parent link="right_tool0"/>
                <child link="rgripper_robotiq_arg2f_base_link"/>
                <origin xyz="0 0 0" rpy="0 0 ${pi / 2}"/>
            </joint>
        </xacro:if>

        <!--Kinect-->
        <xacro:if value="${sim}">
            <!-- position of kinect has to be changed in common_sensors/urdf/sensors/kinect_properties.urdf.xacro-->
            <xacro:include filename="$(find hiro_core)/urdf/sensors/kinect.urdf.xacro"/>
            <xacro:sensor_kinect parent="body_base_link"/>
        </xacro:if>
    </xacro:macro>

    <xacro:xamyab_robot joint_limited="${limited}" grippers="${grippers}"/>

</robot>